# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'FirebaseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseDemo
pod 'GoogleSignIn'
pod 'Firebase/Auth'

end
